# release.yml

changelog:
  categories:
    - title: 🚀 Exciting New Features
      labels:
        - feature
    - title: ✅ Tests
      labels:
        - tests
    - title: 🐛 Bugs fixed
      labels:
        - bug
    - title: 🔧 Refactor
      labels:
        - refactor
    - title: ⚙️ Behind the scenes
      labels:
        - "*"
