- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present
    - name: Setup nginx conf
      template:
        src=nginx.conf.tpl
        dest=/etc/nginx/nginx.conf
    - name: Chown /app/web
      file:
        path: /app/web
        owner: nginx
        recurse: yes
        state: directory
  handlers:
    - name: restart nginx
      service:
        name=nginx
        state=restarted
