plugins:
  duplication:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-4"
    checks:
      complexity:
        enabled: false
  csslint:
    enabled: false

ratings:
  paths:
    - "web/src/**"
