engines:
  duplication:
    enabled: false
    config:
      languages:
        - javascript:

  eslint:
    enabled: true
    channel: 'eslint-8'
  csslint:
    enabled: false

ratings:
  paths:
    - 'web/src/**'
    - 'api/**'
