version: '3.2'
services:
  db:
    image: postgres:10.18-bullseye
    environment:
      - POSTGRES_DB=hitech_apd_test
      - POSTGRES_PASSWORD=cms
    expose:
      - 5432
    ports:
      - '55432:5432'

  mongo:
    image: mongo:5.0.9
    environment:
      - MONGO_DATABASE=eapd-test
      - MONGO_DATABASE_PASSWORD=cms-test
      - MONGO_DATABASE_USERNAME=mongo-test
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
      - MONGO_INITDB_ROOT_USERNAME=admin-user
    volumes:
      - ./api/db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    command: [--auth]
    ports:
      - 27018:27017

  api-for-testing:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: cms-eapd/api
    container_name: api-container
    depends_on:
      - db
      - mongo
    environment:
      - API_HOST=api-for-testing
      - API_PORT=8000
      - ENDPOINT_COVERAGE_CAPTURE=true
      - FILE_PATH=test-data/files
      - FILE_STORE=local
      - MONGO_ADMIN_URL=mongodb://admin-user:admin-password@mongo:27017/admin
      - MONGO_AUTH_SOURCE=admin
      - MONGO_DATABASE=eapd-test
      - MONGO_URL=mongodb://mongo-test:cms-test@mongo:27017/eapd-test?authSource=admin
      - NODE_ENV=test
      - PORT=8000
      - JWT_SECRET=${JWT_SECRET}
      - LD_API_KEY=${LD_API_KEY}
      - OKTA_API_KEY=${OKTA_API_KEY}
      - OKTA_AUDIENCE=${OKTA_AUDIENCE}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_SERVER_ID=${OKTA_SERVER_ID}
    command: yarn start
    expose:
      - 8000
    volumes:
      - api:/app/api # This can't be ./api:/app/api in CI/CD
      - common:/app/common # This can't be ./common:/app/common in CI/CD
      - /app/node_modules

volumes:
  api:
  common:
