version: "3.2"
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=hitech_apd
      - POSTGRES_PASSWORD=cms
      - PGDATA=/pgdata
    volumes:
      - type: bind
        source: ./pgdata
        target: /pgdata
        consistency: delegated
    expose:
      - 5432
    ports:
      - 54325:5432

  web:
    build: ./web
    image: cms-eapd/web
    environment:
      - API_URL=http://localhost:8081
    volumes:
      - type: bind
        source: ./web
        target: /app
        consistency: delegated
      - /app/node_modules
    ports:
      - 8080:8001

  api:
    build: ./api
    image: cms-eapd/api
    depends_on:
      - db
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://postgres:cms@db/hitech_apd
      - NODE_ENV=development
      - DISABLE_SAME_SITE=yes
    volumes:
      - type: bind
        source: ./api
        target: /app
        consistency: delegated
      - /app/node_modules
    ports:
      - 8081:8000
