version: "3"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=hitech_apd
      - POSTGRES_PASSWORD=cms
    expose:
      - 5432
    ports:
      - 54325:5432

  web:
    build: ./web
    environment:
      - API_URL=http://localhost:8081
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - 8080:8001

  api:
    build: ./api
    depends_on:
      - db
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://postgres:cms@db/hitech_apd
      - NODE_ENV=development
      - SESSION_SECRET=super-secret-docker-secret-shhhh
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - 8081:8000
