version: "3.2"
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=hitech_apd
      - POSTGRES_PASSWORD=cms
      - PGDATA=/pgdata
    volumes:
      - pgdata:/pgdata
    expose:
      - 5432
    ports:
      - 54325:5432

  web:
    build: ./web
    image: cms-eapd/web
    environment:
      - API_URL=http://localhost:8081
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_SERVER_ID=${OKTA_SERVER_ID}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
    volumes:
      - type: bind
        source: ./web
        target: /app
        consistency: delegated
      - /app/node_modules
    ports:
      - 8080:8001

  api:
    build: ./api
    image: cms-eapd/api
    depends_on:
      - db
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://postgres:cms@db/hitech_apd
      - NODE_ENV=development
      - DISABLE_SAME_SITE=yes
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_SERVER_ID=${OKTA_SERVER_ID}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_API_KEY=${OKTA_API_KEY}
    volumes:
      - type: bind
        source: ./api
        target: /app
        consistency: delegated
      - /app/node_modules
    ports:
      - 8081:8000
      - 9229:9229

volumes:
  pgdata:
