version: "3"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=hitech_apd
      - POSTGRES_PASSWORD=cms
      - PGDATA=/pgdata
    volumes:
      - ./pgdata:/pgdata
    expose:
      - 5432
    ports:
      - 54325:5432

  web:
    build: ./web
    environment:
      - API_URL=http://localhost:8081
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - 8080:8001
  
  storybook:
    build: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    command: npm run storybook
    ports:
      - 8082:9001

  api:
    build: ./api
    depends_on:
      - db
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://postgres:cms@db/hitech_apd
      - NODE_ENV=development
      - SESSION_SECRET=dadccbf1e3bcb63a4d533c3f184eecfc79fd07e76d0584f808078125a83bc40b6413829e5c690d391dd3f6cbca44406cef07b8193cd4db2f03bab355eea9cb2e
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - 8081:8000
