version: '3.2'
services:
  db:
    image: postgres:10.18-bullseye
    environment:
      - PGDATA=/pgdata
      - POSTGRES_DB=hitech_apd
      - POSTGRES_PASSWORD=cms
    volumes:
      - pgdata:/pgdata
    expose:
      - 5432
    ports:
      - 54325:5432

  mongo:
    image: mongo:5.0.9
    environment:
      - MONGO_DATABASE=eapd
      - MONGO_DATABASE_PASSWORD=cms
      - MONGO_DATABASE_USERNAME=mongo
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
      - MONGO_INITDB_ROOT_USERNAME=admin-user
    volumes:
      - mongodata:/mongodata
      - ./api/db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    command: [--auth]
    ports:
      - 27017:27017

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    image: cms-eapd/web
    restart: unless-stopped
    environment:
      - API_URL=http://localhost:8081
      - LD_CLIENT_ID=${LD_CLIENT_ID}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_SERVER_ID=${OKTA_SERVER_ID}
      - TEALIUM_ENV=${TEALIUM_ENV:-dev}
      - TEALIUM_TAG=${TEALIUM_TAG:-default}
    volumes:
      - type: bind
        source: ./web
        target: /app/web
        consistency: cached
      - type: bind
        source: ./common
        target: /app/common
        consistency: cached
      - /app/node_modules

    ports:
      - 8080:8001

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: cms-eapd/api
    restart: unless-stopped
    depends_on:
      - db
      - mongo
    environment:
      - DISABLE_SAME_SITE=yes
      - NODE_ENV=development
      - PORT=8000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEV_DB_NAME=${DEV_DB_NAME:-hitech_apd}
      - FILE_S3_BUCKET=${FILE_S3_BUCKET}
      - FILE_PATH=${FILE_PATH:-test-data/files}
      - FILE_STORE=${FILE_STORE:-local}
      - JWT_SECRET=${JWT_SECRET}
      - LD_API_KEY=${LD_API_KEY}
      - MONGO_ADMIN_URL=${MONGO_ADMIN_URL:-mongodb://admin-user:admin-password@mongo:27017/admin}
      - MONGO_AUTH_SOURCE=${MONGO_AUTH_SOURCE:-admin}
      - MONGO_DATABASE=${MONGO_DATABASE:-eapd}
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:cms@mongo:27017/eapd?authSource=admin}
      - OKTA_API_KEY=${OKTA_API_KEY}
      - OKTA_AUDIENCE=${OKTA_AUDIENCE}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_SERVER_ID=${OKTA_SERVER_ID}
      - TEST_DB_NAME=${TEST_DB_NAME:-hitech_apd_test}
    volumes:
      - type: bind
        source: ./api
        target: /app/api
        consistency: cached
      - type: bind
        source: ./common
        target: /app/common
        consistency: cached
      - /app/node_modules
    ports:
      - 8081:8000
      - 9229:9229

volumes:
  pgdata:
  mongodata:
