version: '3.2'
services:
  db:
    image: postgres:10.18-bullseye
    environment:
      - POSTGRES_DB=hitech_apd
      - POSTGRES_PASSWORD=cms
    expose:
      - 5432
    ports:
      - '54325:5432'

  mongo:
    image: mongo:5.0.3
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=admin-user
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
      - MONGO_INITDB_DATABASE=eapd
      - DATABASE_USERNAME=mongo
      - DATABASE_PASSWORD=cms
    volumes:
      - ../api/db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    command: [--auth]
    ports:
      - 27019:27017
  web:
    build: ../web
    image: cms-eapd/web
    environment:
      - API_URL=http://localhost:8081
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_SERVER_ID=${OKTA_SERVER_ID}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
    volumes:
      - type: bind
        source: ../web
        target: /app
        consistency: delegated
      - /app/node_modules
    ports:
      - 8080:8001

  api:
    build: ../api
    image: cms-eapd/api
    depends_on:
      - db
    environment:
      - PORT=8000
      - NODE_ENV=development
      - FILE_STORE=local
      - FILE_PATH=test-data/files
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_SERVER_ID=${OKTA_SERVER_ID}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_API_KEY=${OKTA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URL=mongodb://mongo:cms@mongo:27017/eapd?authSource=eapd
      - MONGO_DATABASE=eapd
    command: npm start
    expose:
      - 8000
    volumes:
      - type: bind
        source: ../api
        target: /app
        consistency: delegated
      - /app/node_modules

networks:
  default:
    name: eapd_e2e
