version: '3'
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=hitech_apd_test
      - POSTGRES_PASSWORD=cms
    expose:
      - 5432
    ports:
      - "55432:5432"

  api-for-testing:
    image: cms-eapd/api
    depends_on:
      - db
    environment:
      - PORT=8000
      - NODE_ENV=test
      - API_PORT=8000
      - API_HOST=api-for-testing
      - ENDPOINT_COVERAGE_CAPTURE=${ENDPOINT_COVERAGE_CAPTURE}
      - FILE_STORE=local
      - FILE_PATH=test-data/files
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_SERVER_ID=${OKTA_SERVER_ID}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_API_KEY=${OKTA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    command: npm start
    expose:
      - 8000
    volumes:
      - ./:/app
      - /app/node_modules
