version: "3"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=hitech_apd_test
      - POSTGRES_PASSWORD=cms
    expose:
      - 5432

  api-endpoint-tests:
    build: ./
    depends_on:
      - db
    environment:
      - PORT=8000
      - NODE_ENV=test
    volumes:
      - ./:/app
      - /app/node_modules
    # entrypoint: ./test/endpoint-tests.sh
