# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  pull_request:
    branches:
      - main

# List of jobs
jobs:
  chromatic:
    # Operating System
    runs-on: ubuntu-18.04
    environment: Preview
    timeout-minutes: 60
    # Job steps
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
      - name: Install
        run: |
          cd web
          yarn install
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GH_TOKEN }}
