name: Cleanup Test/Preview Deploys
on:  [push]
#  schedule:
#    - cron: '0 0 * * *'  # every day at midnight
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']
    steps:
    - name: Checkout Repo 🛎️
      uses: actions/checkout@v2
    - name: Configure AWS Credentials ☁️
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.TEST_AWS_REGION }}   
    - name: Set up Python ${{ matrix.python-version }} 🐍
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies 💿
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install jq -y
        pip install --quiet awscli
    - name: Cleanup Test/Preview Deploys w/No Open PR 🚿
      env:
        API_AWS_REGION: ${{ secrets.TEST_AWS_REGION }}
        GH_BOT_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      run: |
        ./bin/preview-deploy/aws.cleanup.sh \
