name: Cypress E2E Tests
on:
#  schedule:
#    - cron: '0 0 * * *'  # every day at midnight
  push:
    branches:
      - bbrooks/3227-Cypress-CI

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup npm package Frontend
        working-directory: ./web
        run: |
          npm ci
          npm install
          npm run start -- --public=0.0.0.0:8080 &
      - name: Setup npm package Backend
        environment: Test
        working-directory: ./api
        env:
          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}
        run: |
          npm ci
          npm install
          npm run start-dev &       
      - name: Run E2E test
        uses: cypress-io/github-action@v2
        env:
          NODE_ENV: development
        with:
          working-directory: ./integrationTests
          browser: chrome
          headless: true
        