name: Cypress E2E Tests
on:
  schedule:
    - cron: '0 1 * * *' # every day at 1 am
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    environment: Preview
    runs-on: ubuntu-18.04
    timeout-minutes: 150
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Starting Dockerized eAPD App
        working-directory: ./
        env:
          NODE_ENV: development
          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}
          OKTA_SERVER_ID: ${{ secrets.OKTA_SERVER_ID }}
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DOCKER_EAPD_UN: ${{ secrets.DOCKER_EAPD_UN }}
          DOCKER_EAPD_PW: ${{ secrets.DOCKER_EAPD_PW }}
        run: |
          docker login -u $DOCKER_EAPD_UN -p $DOCKER_EAPD_PW
          docker-compose up -d
          docker-compose exec -T api npm run migrate
          docker-compose exec -T api npm run seed
      - name: Cypress setup
        working-directory: ./integrationTests
        env:
          NODE_ENV: development
          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}
          OKTA_SERVER_ID: ${{ secrets.OKTA_SERVER_ID }}
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CYPRESS_ENV: ${{ secrets.CYPRESS_ENV }}
        run: |
          npm ci
          sh cypress-ci-setup.sh
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          config-file: ./integrationTests/cypress.json
          wait-on: 'http://localhost:8080'
          headless: true
          record: true
          parallel: true
          group: 'Actions example'
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
