name: Cypress E2E Tests
on:
  schedule:
    - cron: '0 1 * * *' # every day at 1 am
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    environment: Preview
    runs-on: ubuntu-18.04
    timeout-minutes: 150
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: ['@apd+@default', '@apd+@data', '@admin; @auth']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker GitHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_CYPRESS_UN }}
          password: ${{ secrets.DOCKER_CYPRESS_PW }}
      - name: Starting Dockerized eAPD App
        working-directory: ./
        env:
          NODE_ENV: development
          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}
          OKTA_SERVER_ID: ${{ secrets.OKTA_SERVER_ID }}
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          docker-compose up -d
          docker-compose exec -T api npm run migrate
          docker-compose exec -T api npm run seed
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
      - name: Cypress tests
        uses: cypress-io/github-action@v2.9.7
        with:
          working-directory: ./integrationTests
          browser: chrome
          config-file: cypress.json
          install-command: npm ci && sh cypress-ci-setup.sh
          build: npx cypress info
          command: npx cypress run --env grepTags=${{ matrix.containers }}
          wait-on: 'http://localhost:8080, http://localhost:8081/heartbeat'
          wait-on-timeout: 300
          headless: true
          record: true
          tag: ${{ matrix.containers }}
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
        env:
          NODE_ENV: development
          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}
          OKTA_SERVER_ID: ${{ secrets.OKTA_SERVER_ID }}
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CYPRESS_ENV: ${{ secrets.CYPRESS_ENV }}
          # pass the Dashboard record key as an environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
