name: Cypress E2E Tests
on:
#  schedule:
#    - cron: '0 0 * * *'  # every day at midnight
  push:
    branches:
      - bbrooks/3227-Cypress-CI

jobs:
  cypress-run:
    environment: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Setup npm package Frontend
#        working-directory: ./web
#        run: |
#          npm ci
#          npm install
#          npm run start -- --public=0.0.0.0:8080 &
#      - name: Setup npm package Backend
#        working-directory: ./api
#        env:
#          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
#          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}
#        run: |
#          npm ci
#          npm install
#          npm run start-dev &       
      - name: Cypress Dependency
        working-directory: ./integrationTests
        env:
          NODE_ENV: development
        run: |
          npm install knex
          docker-compose exec api npm run migrate
          docker-compose exec api npm run seed
      - name: Testing different method
        working-directory: ./integrationTests
        env:
          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}
        run: |
          sh cypress-setup.sh run
      - name: Run E2E test
        if: ${{ always() }}
        uses: cypress-io/github-action@v2
        env: host=api.dev.local,port=8080
          NODE_ENV: development
        with:
          working-directory: ./integrationTests
          browser: chrome
          headless: true
          env: 
      - name: Debugging Info
        working-directory: ./integrationTests
        run: |
          ls -la
          pwd
          find ./ -type f -name index.js
