name: Cypress E2E Tests
on:
#  schedule:
#    - cron: '0 0 * * *'  # every day at midnight
  push:
    branches:
      - bbrooks/3227-Cypress-CI

jobs:
  cypress-run:
    environment: Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress Dependency
        env:
          NODE_ENV: development
          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}          
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
#          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb postgresql postgresql-contrib
          npm install knex
#          npm install pg
#          npm install cypress
#          npm install
#      - name: Cypress Dependency Web
#        env:
#          NODE_ENV: development
#          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
#          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}          
#        run: |
#          npm install knex
#          npm install pg
#          npm install cypress
#          npm install
#      - name: Cypress Dependency integrationTests
#        env:
#          NODE_ENV: development
#          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
#          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}          
#        run: |
#          npm install knex
#          npm install pg
#          npm install cypress
#          npm install                    
      - name: Cypress E2E Tests
        working-directory: ./integrationTests
        env:
          NODE_ENV: development
          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}
          OKTA_SERVER_ID: ${{ secrets.OKTA_SERVER_ID }}
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
#          DEV_DB_HOST: 
#          DEV_DB_USER: 
#          DEV_DB_PASSWORD: 
        run: |
          sh cypress-ci.sh

