name: Dependency Vulnerability Scans
on:
  schedule:
    - cron: '30 0 * * *' # every day at 12:30 am

jobs:
  install-dependencies:
    environment: Preview
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - name: Cache Node Modules 💾
        uses: actions/cache@v2
        with:
          path: ./.yarnrc
          key: cms-hitech-apd-yarn-{{ checksum "yarn.lock" }}
          restore-keys: cms-hitech-apd-yarn-{{ checksum "yarn.lock" }}

      - name: Checkout Repo 🛎️
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: .
        run: |
          yarn install --frozen-lockfile
      - name: Tar and Zip Node Modules
        working-directory: .
        run: |
          tar -cvzf node-modules.tar.gz ./node_modules
          ls -la
          pwd
      - name: Upload Node Modules
        uses: actions/upload-artifact@v2
        with:
          name: node-modules
          path: node-modules.tar.gz

  dependency-vulnerability-scan:
    environment: Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    steps:
      - name: Cache Node Modules 💾
        uses: actions/cache@v2
        with:
          path: ./.yarnrc
          key: cms-hitech-apd-yarn-{{ checksum "yarn.lock" }}
          restore-keys: cms-hitech-apd-yarn-{{ checksum "yarn.lock" }}

      - name: Checkout Repo 🛎️
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: .
        run: |
          yarn install --frozen-lockfile
      - name: Tar and Zip Node Modules
        working-directory: .
        run: |
          tar -cvzf node-modules.tar.gz ./node_modules
          ls -la
          pwd
      - name: Upload Node Modules 🕸️
        uses: actions/upload-artifact@v2
        with:
          name: node-modules
          path: node-modules.tar.gz

      - name: Retrieve Cached Frontend Modules
        uses: actions/download-artifact@v2
        with:
          name: node-modules
          path: .
      - name: Unarchieve and zip Node Modules
        working-directory: ./
        run: |
          ls -la
          pwd
          tar xzvf node-modules.tar.gz
      - name: Vulnerability Scan
        working-directory: .
        run: |
          ls -la
          pwd
          yarn run audit
    needs: install-dependencies
