name: Cypress Tests
on:
#  schedule:
#    - cron: '0 0 * * *'  # every day at midnight
  push:
    branches:
      - bbrooks/3227-Cypress-CI

jobs:  
  install-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14']
    steps:
      - name: Cache Node Modules 💾
        uses: actions/cache@v2
        with:
          path: ./.npm
          key: cms-hitech-apd-npm-{{ checksum "web/package-lock.json" }}-{{ checksum "api/package-lock.json" }}
          restore-keys: cms-hitech-apd-npm-{{ checksum "web/package-lock.json" }}-{{ checksum "api/package-lock.json" }}

      - name: Checkout Repo 🛎️
        uses: actions/checkout@v2

      - name: Install Web Dependencies 🕸️
        working-directory: ./web
        run: |
          npm ci
      - name: Tar and Zip Frontend Node Modules
        working-directory: ./web
        run: |
          tar -cvzf frontend-modules.tar.gz ./node_modules
          ls -la
          pwd
      - name: Upload Frontend Node Modules 🕸️
        uses: actions/upload-artifact@v2
        with:
          name: frontend-modules
          path: web/frontend-modules.tar.gz

      - name: Install API Dependencies ✨
        working-directory: ./api
        run: |
          npm ci
      - name: Tar and Zip Backend Node Modules
        working-directory: ./api
        run: |
          tar -cvzf backend-modules.tar.gz ./node_modules
          ls -la
          pwd
      - name: Upload Frontend Node Modules 🕸️
        uses: actions/upload-artifact@v2
        with:
          name: frontend-modules
          path: api/backend-modules.tar.gz
      - name: Upload Backend Node Modules ✨
        uses: actions/upload-artifact@v2
        with:
          name: backend-modules
          path: api/backend-modules.tar.gz


  dependency-vulnerability-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14']
    steps:
      - name: Cache Node Modules 💾
        uses: actions/cache@v2
        with:
          path: ./.npm
          key: cms-hitech-apd-npm-{{ checksum "web/package-lock.json" }}-{{ checksum "api/package-lock.json" }}
          restore-keys: cms-hitech-apd-npm-{{ checksum "web/package-lock.json" }}-{{ checksum "api/package-lock.json" }}

      - name: Checkout Repo 🛎️
        uses: actions/checkout@v2

      - name: Install Web Dependencies 🕸️
        working-directory: ./web
        run: |
          npm ci
      - name: Tar and Zip Frontend Node Modules
        working-directory: ./web
        run: |
          tar -cvzf frontend-modules.tar.gz ./node_modules
          ls -la
          pwd
      - name: Upload Frontend Node Modules 🕸️
        uses: actions/upload-artifact@v2
        with:
          name: frontend-modules
          path: web/frontend-modules.tar.gz

      - name: Retrieve Cached Frontend Modules
        uses: actions/download-artifact@v2
        with:
          name: frontend-modules
          path: web/
      - name: Unarchieve and zip Frontend Node Modules
        working-directory: ./web/
        run: |
          ls -la
          pwd
          tar xzvf frontend-modules.tar.gz
      - name: Frontend Vulnerability Scan 🕸️
        working-directory: ./web
        run: |
          ls -la
          pwd
          npm run audit


      - name: Install API Dependencies ✨
        working-directory: ./api
        run: |
          npm ci
      - name: Tar and Zip Backend Node Modules
        working-directory: ./api
        run: |
          tar -cvzf backend-modules.tar.gz ./node_modules
          ls -la
          pwd

      - name: Retrieve Cached Backend Modules
        uses: actions/download-artifact@v2
        with:
          name: backend-modules
          path: api/
      - name: Unarchieve and zip Backend Node Modules
        working-directory: ./api/
        run: |
          ls -la
          pwd
          tar xzvf backend-modules.tar.gz
      - name: Backend Vulnerability Scan ✨
        working-directory: ./api
        run: |
          ls -la
          pwd
          npm run audit
    needs: install-dependencies

  cypress-run-headless:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14']
    environment: Test
    steps:
      - name: Cache Node Modules 💾
        uses: actions/cache@v2
        with:
          path: ./.npm
          key: cms-hitech-apd-npm-{{ checksum "web/package-lock.json" }}-{{ checksum "api/package-lock.json" }}
          restore-keys: cms-hitech-apd-npm-{{ checksum "web/package-lock.json" }}-{{ checksum "api/package-lock.json" }}

      - name: Checkout Repo 🛎️
        uses: actions/checkout@v2

      - name: Install Web Dependencies 🕸️
        working-directory: ./web
        run: |
          npm ci
          npm run start -- --public=0.0.0.0:8080 &

      - name: Install API Dependencies ✨
        working-directory: ./api
        env: 
          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
          OKTA_API_KEY: ${{ secrets.OKTA_API_KEY }}
        run: |
          npm ci
          npm install
          npm run start-dev &

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      
      - name: Checkout Repo 🛎️
        uses: actions/checkout@v2

      - name: Cypress Run Frontend
        uses: cypress-io/github-action@v2
        with:
#          record: true
          working-directory: ./integrationTests
          browser: chrome
          headless: true
#          project: ./web
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_ENV: development

      - name: Cypress Run Backend
        uses: cypress-io/github-action@v2
        with:
#          record: true
          working-directory: ./integrationTests
          browser: chrome
          headless: true
#          project: ./api
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_ENV: development
    needs: 
      - install-dependencies
      - dependency-vulnerability-scan
