name: Create Platinum AMI
on:
  push: 
    branches: bbrooks/environment_vulnerability_scans
#  schedule:
#    - cron: '0 0 * * 1'  # Mondays at midnight
jobs:
  packer:
    runs-on: ubuntu-latest
    environment: Preview    
    timeout-minutes: 60    
    name: packer
    steps:
      - name: Checkout Repository 🛎️
        uses: actions/checkout@v2
      - name: Configure AWS Credentials ☁️
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}   
      - name: Validate Template ✔️
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          working_directory: packer
          target: plat-ami.pkr.hcl
      # build artifact
      - name: Build Artifact 🧱
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          working_directory: packer
          target: plat-ami.pkr.hcl
        env:
          PACKER_LOG: 1
          PKR_VAR_ami_name: ${{ secrets.PACKER_AMI_NAME }}
          PKR_VAR_subnet_id: ${{ secrets.PACKER_SUBNET_ID }}
          PKR_VAR_vpc_id: ${{ secrets.PACKER_VPC_ID }}
          PKR_VAR_gold_owner: ${{ secrets.PACKER_GOLD_OWNER }}
          
