name: Build Preview AMI from CMS Gold AMI using Packer
environment: Test
on:  
  push
#  schedule:
#    - cron: '0 0 * * *'  # every day at midnight
# Add AWS Creds
jobs:
  packer-ami-build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v2
        #Packer Build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1    
      - name: Clean Up Old AMIs
        run: | 
          ./bin/preview-deploy/aws.cleanup.sh
