name: Deploy Storybook
on:
  push:
    branches:
      - tforkner/2909-storybook
jobs:
  storybook-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Install
        run: |
          cd web
          npm install
      - name: Build
        run: |
          cd web
          npm run build-storybook
      - name: Deploy
        run: |
          cd web
          npm run deploy-storybook -- --ci