name: Deploy Storybook
on:
  pull_request:
    branches:
      - main

jobs:
  storybook-deploy:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: web
    environment: Preview
    timeout-minutes: 60
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
      - name: Install and Build
        run: |
          cd web
          yarn install
          yarn build:storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs-build # The folder that the build:storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GH_TOKEN }}
          storybookBuildDir: docs-build
          allowConsoleErrors: true
