name: Deploy Storybook
on:
  push:
    branches:
      - tforkner/2909-storybook
jobs:
  storybook-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          cd web
          npm install
          npm run deploy-storybook -- --ci