name: Deploy Storybook
on:
  push:
    branches:
      - master
      - development
    paths:
      - 'web/.storybook/**'
      - 'web/src/stories/**'
      - 'web/src/**/*.story.js'
      - 'web/src/**/*.story.mdx'
jobs:
  storybook-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Install
        run: |
          cd web
          npm install
      - name: Build
        run: |
          cd web
          npm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs-build # The folder the action should deploy.
