name: Deploy Storybook
on:
  pull_request:
    types:
      - closed
    paths:
      [
        'web/.storybook/**',
        'web/src/stories/**',
        'web/src/**/*.stories.js',
        'web/src/**/*.stories.mdx',
        'web/src/components/**',
        'web/src/containers/**'
      ]

jobs:
  storybook-deploy:
    runs-on: ubuntu-18.04
    environment: Preview
    timeout-minutes: 60
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
      - name: Install Dependencies and Build Storybook
        working-directory: ./web
        run: |
          yarn install --frozen-lockfile
          yarn build:storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GH_TOKEN }}
          storybookBuildDir: docs-build
          allowConsoleErrors: true
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs-build # The folder that the build:storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
