name: Deploy Storybook
on:
  push:
    paths:
      [
        'web/.storybook/**',
        'web/src/stories/**',
        'web/src/**/*.story.js',
        'web/src/**/*.story.mdx',
        'web/src/components/**',
        'web/src/containers/**'
      ]
jobs:
  storybook-deploy:
    runs-on: ubuntu-18.04
    environment: Preview
    timeout-minutes: 60
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          cd web
          npm install
          npm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages # The branch the action should deploy to.
          # folder: docs-build # The folder the action should deploy.
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          # BRANCH: main # The branch the action should deploy to.
          FOLDER: docs-build # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs # The folder that we serve our Storybook files from
